# Discussion metadata
topic: "Code Review Refactoring for Vibe Coding Era"
created: 2026-01-04
current_round: 9

# Stale detection configuration
max_stale_rounds: 3

# Decision tracking
decisions:
  - id: D1
    title: "Agent Review Protocol v0.3"
    status: confirmed
    confirmed_at: 3  # Confirmed in R3
    doc_path: ./decisions/D01-agent-review-protocol.md

  - id: D2
    title: "Data Acquisition Strategy - Hook + Skill Dual-Track"
    status: confirmed
    confirmed_at: 5  # Confirmed in R5
    doc_path: ./decisions/D02-data-acquisition-strategy.md

  - id: D3
    title: "Skill and Rule Collaboration"
    status: confirmed
    confirmed_at: 6  # Confirmed in R6
    doc_path: ./decisions/D03-skill-rule-collaboration.md

  - id: D4
    title: "MVP Strategy - Phased Implementation"
    status: confirmed
    confirmed_at: 7  # Confirmed in R7
    doc_path: ./decisions/D04-mvp-strategy.md

  - id: D5
    title: "Open Source Project Positioning"
    status: confirmed
    confirmed_at: 4  # Confirmed in R4
    doc_path: null  # Content in outline, not written separately

  - id: D6
    title: "Product Architecture - 4-Layer Architecture"
    status: confirmed
    confirmed_at: 4  # Confirmed in R4
    doc_path: null  # Content in outline, not written separately

  - id: D7
    title: "Project Naming - Vibe Review"
    status: confirmed
    confirmed_at: 5  # Confirmed in R5
    doc_path: null  # Simple decision, no separate document needed

# Deferred issues
deferred:
  - id: Q3
    title: "How to establish and measure trust in the new paradigm"
    deferred_at: 8  # Deferred in R8
    reason: "MVP phase focuses on 'understanding', trust measurement needs data accumulation"
    note: "Confidence field reserved in protocol"

# Pending issues (cleared - all confirmed in R9)
pending: []

# R9 new decisions (2026-01-26)
# See: ../2026-01-26/contributor-detection/meta.yaml
r9_decisions:
  - id: D8
    title: "Contributor Detection Mechanism"
    confirmed_at: 9
    doc_path: ../2026-01-26/contributor-detection/outline.md
  - id: D9
    title: "Display Layer Interaction Design"
    confirmed_at: 9
    doc_path: ../2026-01-26/contributor-detection/outline.md
  - id: D10
    title: "Open Source Strategy - MIT Full Open Source"
    confirmed_at: 9
    doc_path: ../2026-01-26/contributor-detection/outline.md
  - id: D11
    title: "Todo Item Definition - Agent Task Breakdown"
    confirmed_at: 9
    doc_path: ../2026-01-26/contributor-detection/outline.md
