# Discussion Metadata
topic: "Contributor Detection Mechanism and Display Interaction"
created: 2026-01-26
current_round: 2

# Related discussions
related_discussions:
  - path: "../2026-01-04/vibe-review/outline.md"
    topic: "Vibe Review Main Discussion"
    relation: "extends"  # This discussion extends and refines on top of main discussion
    nature: "completion+refinement"  # Fills and refines display layer issues not involved before

# Stale detection configuration
max_stale_rounds: 3

# Decision tracking
decisions:
  - id: D1
    title: "Contributor Detection Mechanism"
    status: confirmed
    confirmed_at: 1  # Confirmed in R1
    doc_path: "decisions/D01-contributor-detection.md"
    details:
      matching_granularity: "hunk"
      algorithm: "levenshtein"
      thresholds:
        pure_ai: 90
        ai_with_human_edit: 70
      configurable: true

  - id: D2
    title: "Interaction Design - Floating Window Solution"
    status: confirmed
    confirmed_at: 1  # Confirmed in R1
    doc_path: "decisions/D02-interaction-floating-window.md"
    details:
      mvp_jump: false
      interaction: "floating_window_with_command_hints"
      command_template: "post_mvp"

  - id: D3
    title: "Open Source Strategy - MIT Full Open Source"
    status: confirmed
    confirmed_at: 2  # Confirmed in R2
    doc_path: "decisions/D03-open-source-strategy.md"
    details:
      license: "MIT"
      scope: "all"  # Protocol specification, tool layer, product core layer, product delivery layer

  - id: D4
    title: "Todo Item Definition - Agent Task Breakdown"
    status: confirmed
    confirmed_at: 2  # Confirmed in R2
    doc_path: "decisions/D04-todo-definition.md"
    details:
      definition: "Task breakdown generated by Agent itself"

# Issues to resolve
pending: []
